name: Deploy Update Set to Demo3

on:
  push:
    paths:
      - 'update_sets/**/*.xml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get updated file
        id: changes
        run: |
          FILE=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA | grep 'update_sets/.*\.xml' || true)
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Call Demo3 API
        if: steps.changes.outputs.file != ''
        run: |
          echo "Deploying ${{ steps.changes.outputs.file }}"

          curl -X POST https://demo3.service-now.com/api/ays/import_update_set/import \
            -H "Authorization: Basic ${{ secrets.SN_BASIC_AUTH }}" \
            -H "Content-Type: application/json" \
            -d @<(jq -n \
                  --arg name "${{ steps.changes.outputs.file }}" \
                  --arg xml "$(base64 -w 0 ${{ steps.changes.outputs.file }})" \
                  '{name: $name, xml_base64: $xml}')
