name: Deploy Update Set to Demo3

on:
  push:
    paths:
      - 'update_sets/**/*.xml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Trigger Import Job on ServiceNow Demo3
        env:
          SN_INSTANCE: agreeyasolutionsincdemo3
          SN_USER: ${{ secrets.SN_USER }}       # Set in GitHub Secrets
          SN_PASSWORD: ${{ secrets.SN_PASSWORD }} # Set in GitHub Secrets
        run: |
          echo "Triggering ServiceNow Import Scheduled Job..."

          AUTH_HEADER=$(echo -n "$SN_USER:$SN_PASSWORD" | base64)

          curl -X POST "https://$SN_INSTANCE.service-now.com/api/ays/import_update_set/import" \
            -H "Authorization: Basic $AUTH_HEADER" \
            -H "Content-Type: application/json" \
            -d '{}'
