name: Push Update Set to GitHub

on:
  push:
    paths:
      - "update_sets/*.xml"

jobs:
  no-op:
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge Push
        run: echo "✅ Update set XML pushed to GitHub. Demo3 will auto-import and commit it via scheduled job."
